//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Actuarialvaluations.Models.AIValuations
{
    public partial class MarkovStates
    {
        public int ID { get; set; }

        [Required]
        [StringLength(255)]
        public string Applicable_Model_ID { get; set; }

        public int From_State_ID { get; set; }

        public int To_State_ID { get; set; }

        public int PeriodMonthlyIncrements { get; set; }

        [Column(TypeName = "decimal(18, 2)")]
        public decimal IndependantValue { get; set; }
    }
}
