//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Actuarialvaluations.Models.AIValuations
{
    public partial class Models
    {
        public int ID { get; set; }

        [Required]
        [StringLength(255)]
        public string ModelID { get; set; }

        [Required]
        [StringLength(1000)]
        public string Name { get; set; }
    }
}
