//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actuarialvaluations.Models.AIValuations
{
  using System;
  using Microsoft.AspNet.OData.Builder;
  using Microsoft.OData.Edm;

  /// <summary>
  /// <see cref="AIValuationsModelBuilder"/> exposes methods to allow OData support for <see cref="AIValuationsContext"/>.
  /// </summary>
  public sealed class AIValuationsModelBuilder
  {
    /// <summary>
    /// Gets the EDM Model
    /// </summary>
    /// <param name="serviceProvider">The service provider</param>
    /// <returns>The EDM Model</returns>
    public IEdmModel GetEdmModel(IServiceProvider serviceProvider)
    {
      ODataConventionModelBuilder builder = new ODataConventionModelBuilder(serviceProvider);

      builder.EntitySet<Benefits>(nameof(Benefits)).EntityType.Filter().Count().Expand().OrderBy().Page().Select();
      builder.EntitySet<MarkovRateInputValues>(nameof(MarkovRateInputValues)).EntityType.Filter().Count().Expand().OrderBy().Page().Select();
      builder.EntitySet<MarkovStates>(nameof(MarkovStates)).EntityType.Filter().Count().Expand().OrderBy().Page().Select();
      builder.EntitySet<ModelPoints>(nameof(ModelPoints)).EntityType.Filter().Count().Expand().OrderBy().Page().Select();
      builder.EntitySet<Yield>(nameof(Yield)).EntityType.Filter().Count().Expand().OrderBy().Page().Select();

      return builder.GetEdmModel();
    }
  }
}