//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Actuarialvaluations.Models.AIValuations
{
    public partial class AIValuationsContext : DbContext
    {
        public AIValuationsContext()
        {
        }

        public AIValuationsContext(DbContextOptions<AIValuationsContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Benefits> Benefits { get; set; }
        public virtual DbSet<MarkovRateInputValues> MarkovRateInputValues { get; set; }
        public virtual DbSet<MarkovStates> MarkovStates { get; set; }
        public virtual DbSet<ModelPoints> ModelPoints { get; set; }
        public virtual DbSet<Yield> Yield { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity<Benefits>(entity =>
            {
                entity.Property(e => e.BenefitType).IsUnicode(false);

                entity.Property(e => e.ModelID).IsUnicode(false);
            });

            modelBuilder.Entity<MarkovStates>(entity =>
            {
                entity.Property(e => e.Applicable_Model_ID).IsUnicode(false);
            });
        }
    }
}
