//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Actuarialvaluations.Models.AIValuations
{
    public partial class Benefits
    {
        public int ID { get; set; }

        [StringLength(255)]
        public string ModelID { get; set; }

        public int? AssociatedMarkovStateID { get; set; }

        [StringLength(255)]
        public string BenefitType { get; set; }

        public bool? AddSubtract { get; set; }

        [Column(TypeName = "decimal(18, 0)")]
        public decimal? Value { get; set; }
    }
}
