//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Actuarialvaluations.Models.AIValuations
{
    public partial class ModelPoints
    {
        public int ID { get; set; }

        public bool? CONT_OPTION_PREMIUM_WAIVER_OPTION { get; set; }

        public bool? PREM_WAVER_IND { get; set; }

        public bool? COMM_TYPE { get; set; }

        public bool? CASH_BACK_IND { get; set; }

        public bool? Grocery_Benefit_REPATRIATION_Benefit { get; set; }

        public bool? TOMBSTONE_Benefit { get; set; }

        public bool? COW_BENEFIT_Benefit { get; set; }

        public bool? EDUCATOR_OPTION { get; set; }
    }
}
