//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Actuarialvaluations.Models.AIValuations
{
    public partial class Yield
    {
        public int ID { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }

        public int Period { get; set; }

        public double ForwardRate { get; set; }

        public double Inflation { get; set; }
    }
}
